"""Read the application's secrets from AWS Secrets Manager at cold start.

Each secret holds one value as a plain string, which is the shape the
app-secrets Terraform module creates: the signing key is generated by Terraform
and the three admin credentials are seeded with a placeholder and then set out
of band. There is no JSON blob to parse.

The values are fetched once per execution environment and cached in module
scope, so a warm Lambda invocation makes no Secrets Manager call. The cache is
keyed by secret name and holds only what was asked for.
"""

from __future__ import annotations

import logging
from typing import Optional

import boto3

logger = logging.getLogger(__name__)

_client = None
_cache: dict[str, str] = {}


def _get_client():
    global _client
    if _client is None:
        _client = boto3.client("secretsmanager")
    return _client


def secret_name(prefix: str, key: str) -> str:
    """Full Secrets Manager name of one secret, matching the module's naming."""
    return f"{prefix.rstrip('/')}/{key}"


def load_secret(name: str) -> Optional[str]:
    """Return one secret's string value, or None if it has no value yet.

    GetSecretValue raises ResourceNotFoundException for two different things:
    a secret that does not exist, and a secret that exists but has never been
    given a version. Only the second is acceptable, and only briefly: it is the
    window between the apply that creates the secret and the copy that fills
    it, and the caller reports the field as missing. A secret that is not there
    at all means a wrong prefix or a deleted secret, which must fail loudly
    rather than turning into a confusing "missing setting" error, so the two
    are told apart with DescribeSecret. Every other error, a denied read, a
    throttle, a decryption failure, propagates untouched.
    """
    if name in _cache:
        return _cache[name]

    client = _get_client()
    try:
        response = client.get_secret_value(SecretId=name)
    except client.exceptions.ResourceNotFoundException:
        try:
            client.describe_secret(SecretId=name)
        except client.exceptions.ResourceNotFoundException:
            logger.error("Secret %s does not exist", name)
            raise
        logger.warning("Secret %s exists but has no value yet", name)
        return None
    except Exception:
        logger.exception("Failed to read secret %s", name)
        raise

    value = response.get("SecretString")
    if value is None:
        logger.error("Secret %s holds binary data, not a string", name)
        raise ValueError(f"Secret {name} must hold a string value")

    _cache[name] = value
    return value


def load_secrets(prefix: str, keys) -> dict[str, str]:
    """Return the value of each key that has one, keyed by the short key name."""
    found = {}
    for key in keys:
        value = load_secret(secret_name(prefix, key))
        if value is not None:
            found[key] = value
    return found


def reset_cache() -> None:
    """Drop the cached client and values. For tests."""
    global _client
    _client = None
    _cache.clear()
